name: FreeEnchanting
version: 1.1.0
main: me.that1guyyyy.FreeEnchanting
api-version: '1.21'
author: that1guyyyy
commands:
  noxp:
    description: Opens the FreeEnchanting configuration menu.
    permission: op

